---
broker:
  logger:
    enabled: true
    plugin: zap
    fields:
      component: broker
    level: trace
client:
  logger:
    enabled: true
    plugin: zap
    fields:
      component: client
    level: trace
server:
  logger:
    enabled: true
    plugin: logrus
    fields:
      component: server
    level: trace
  register_ttl: 30
  register_interval: 60
logger:
  enabled: true
  plugin: zap
  fields:
    component: default
  level: trace
registry:
  logger:
    enabled: true
    plugin: zap
    fields:
      component: registry
    level: trace
transport:
  logger:
    enabled: true
    plugin: zap
    fields:
      component: transport
    level: trace
