---
broker:
  plugin: nats
  addresses:
    - nats://localhost:4222
registry:
  plugin: nats
  addresses:
    - nats://localhost:4222
transport:
  plugin: nats
  addresses:
    - nats://localhost:4222
